version: "3.8"
services:
  db:
    container_name: 'database'
    image: 'postgres:16'
    restart: 'always'
    ports:
      - '5432:5432'
    env_file: 'env/env_db.txt'
    volumes:
      - db:/postgresql
  app:
    container_name: 'application'

volumes:
  db:
    driver: local

